### ISSUE TITLE
Publication year incorrect for manually added articles

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#108]
Publication year is one year off for manually added articles on homepage, search results page, and replication table, but correct for the field below the title; e.g., https://www.curatescience.org/beta/#/articles/60040 appears as 1995 when in fact is 1996 

Publication year is correct everywhere for scraped articles.

**Comment by manzhikov** [comment]
https://github.com/ScienceCommons/www/pull/14

**Comment by manzhikov** [comment]
the problem is because angular used own timezone, probably UTC.
Seems like you are tested it in UTC-8 timezone
Then you parse date 1996-01-01 it is 1995-12-31 16:00 UTC

I made changes in year function to send timezone with text. It should help. But better to set correctly timezone in angular

**Comment by eplebel** [comment]
>>>But better to set correctly timezone in angular

So why don't you do that then @manzhikov ?

p.s. I thought we were using the mithril JS framework rather than angular, no? @alexkyllo

**Comment by alexkyllo** [comment]
Correct, the www app uses mithril.js. 
The user's browser determines the time zone. There is no timezone information for the publication_date field in the database.
The correct way to fix this is probably to specify the user's local time zone when calling the Date object constructor here:
https://github.com/ScienceCommons/www/blob/master/client/models/ArticleModel.js#L121
and here:
https://github.com/ScienceCommons/www/blob/master/client/models/StudyModel.js#L67
This could be accomplished by calling 
`var offset = new Date().getTimezoneOffset();`
which returns the user's offset from UTC in minutes, and then adding/subtracting it from the publication_date.

**Comment by eplebel** [comment]
Thanks for chiming in @alexkyllo .

Ildar and I discussed this over Skype and decided that a simpler and faster way of address this is to change the get('year') function to just get the year from the string, without the date function. I said I was fine with that as long as this fix also works when pulling in article metadata via the PubMed API; Ildar assured me this would be fine. Any thoughts on this @alexkyllo ?

**Comment by alexkyllo** [comment]
Yeah, the issue occurs when you parse the string into a Javascript Date object, so if you avoid that step altogether and just treat it as a string on the client-side that should also resolve the issue. If you don't require the dates to be viewed/formatted/manipulated in the browser in any other way than just showing/entering the year as YYYY then this should be fine.

**Comment by eplebel** [comment]
OK, thanks for the input @alexkyllo !
