### ISSUE TITLE
Add Article page minor UI issues

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#111]
(1) Add a label for year ("Publication year"),  add "YYYY format" inside text box (so user knows how to input the year), and only require year (month & day are typically unknown and more importantly researchers don't care about this so we simply cannot require this from them!).

(2) Add a label for authors ("Authors") and add mouse pointer and tool tip when hovering over plus(+) sign (so user knows how to add an author)

**Comment by alexkyllo** [comment]
Currently if you try to edit the publication date on an existing article you get a 500 server error, so I'm working on fixing that bug.

If you create a Date object with format just YYYY e.g. 2015 it defaults to January 1 and becomes 2015-01-01. Do you want publication dates to always be displayed as just YYYY in the UI even if there was previously a month/day other than 01-01 in the database?

**Comment by alexkyllo** [comment]
I figured out the bug. The ArticlePage (and several other pages) makes use of innerText which is a non-standard attribute that Firefox doesn't support. I'm going to replace all instances of innerText with textContent, as I'm assuming you want this app to work with Firefox.

**Comment by eplebel** [comment]
>>>>Do you want publication dates to always be displayed as just YYYY in the UI even if there was previously a month/day other than 01-01 in the database?

Yes, precisely! And this will also be the case for articles that we pull in automatically via API (e.g., PubMed API), which sometimes will have a month/day.

**Comment by eplebel** [comment]
>Changing the publication date format to be YYYY instead of YYYY-MM-DD will require a change to the rails server-side logic (api repo) so that will take a little longer.

But can't we just leave the publication date format to be YYYY-MM-DD on the rails server/DB, but just display YYYY in the UI? 
And when an article is manually added, we could simply store the publication date as YYYY-01-01 (e.g., 2015 as 2014-01-01, as you mentioned above).
A possible advantage of this approach is that perhaps down the road, we'll discover a use case for wanting to also input/display the month/day (e.g., perhaps for unpublished articles?), and so it would be easier to implement such a change at that point in time.

**Comment by eplebel** [comment]
I should have made this clearer in my original description of the issue, but the "Publication Year" and "Authors" labels should only be displayed in the ADD or EDIT modes of the article page. When simply viewing articles, those labels should *not* be displayed because it's clear what those things are. 

(I now understand why you were asking about the location of those labels; my bad, I guess I misunderstood your question!)

**Comment by alexkyllo** [comment]
Ok, I fixed it to hide the "Publication Year" and "Author" labels when not editing/adding an article. I went ahead and committed & deployed, so you should be able to see the change now. Let me know if this looks good.

**Comment by eplebel** [comment]
Great, thanks so much for the quick fix!!

**Comment by eplebel** [comment]
"Publication Year" and "Author" labels are no longer being hiden when not editing/adding (i.e., viewing) an article. This is probably related to recently deployed changes to the Add article page enhancements. I've now logged this under a new issue #166
