### ISSUE TITLE
Add-article page enhancements

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#141]
Given our currently poor coverage of article meta-data, it's pretty important to substantially enhance the UI for manually adding articles (https://www.curatescience.org/beta/#/articles/new) not yet in our DB (which is the majority of published articles and most replication studies which are often not even published). 
![add-article-page](https://cloud.githubusercontent.com/assets/4512335/5366596/24dbd628-7fc3-11e4-90e9-0eb11c945d28.png)

A very important feature is the automatic retrieval of article metadata (article title, authors, year, journal name, abstract) via CrossRef DOI lookup, which really saves a lot of time for the user. I've got this working in R which uses OpenURL calls. 
For e.g., for the DOI=10.1177/1948550612448196, the OpenURL call would be:
http://www.crossref.org/openurl/?pid=etienne.lebel@gmail.com&format=unixref&id=doi:10.1177/1948550612448196&noredirect=true

which yields :
LeBel E and Campbell L (2012). “The Interactive Role of Implicit and Explicit Partner Evaluations on Ongoing Affective and Behavioral Romantic Realities.” _Social Psychological and Personality Science_, *4*. <URL: http://dx.doi.org/10.1177/1948550612448196>.

Note, that all functionality is already implemented on the current Add Article page, including the add authors and add tags pills functionality (https://www.curatescience.org/beta/#/articles/new).

For the DOI=10.1177/1948550612448196 example, this would populate the fields as follows:
<b>Author(s):</b>{LeBel E} {Campbell L} (each author is a pill; authors are automatically created via pre-existing Author.create function; this will of course create duplicate authors, but these will merged later by editors/administrators via merge tool soon to be built, see issue xx)
<b>Publication year:</b> 2012
<b>Article title:</b> The Interactive Role of Implicit and Explicit Partner Evaluations on Ongoing Affective and Behavioral Romantic Realities
<b>Journal name:</b> Social Psychological and Personality Science

Note for certain DOIs an abstract is available. If so, the abstract text should be populated in the abstract field. Example DOI that has available abstract: 10.1017/S0140525X13000290

<b>More details/clarifications:</b>
For a valid DOI that successfully retrieves article metadata, after user clicks "Retrieve article metadata", the focus should move to the "Save" button (so user can simply hit enter to save article!), and this is what the page should look like for the same DOI example from above (DOI=10.1177/1948550612448196):
![add-article-page-filled-out](https://cloud.githubusercontent.com/assets/4512335/7301324/0f7b3416-e9b0-11e4-8225-150397ec558d.png)

Final note: 
Standard ordered tabbing between fields and buttons should be implemented. That is, from the DOI field, hitting TAB key moves user to "Retrieve article metadata" button; hitting TAB key again moves user to "+" add author icon, then publication year, etc.). Upon page load, cursor focus should be in DOI field so that users can immediately copy-and-paste DOI.

**Comment by alexkyllo** [comment]
pull requests merged and deployed to production 
https://github.com/ScienceCommons/api/pull/169
https://github.com/ScienceCommons/www/pull/12
