### ISSUE TITLE
Invite fail

### ISSUE THREAD

**Issue by cbattista** [ScienceCommons/api#148]
Tried to get one of my colleagues (who has multiple gmail accounts, not sure this is a factor) to get in the system.  Sent invite, they approve the app - but they are taken to the 'sign up' button on the splash page.

Same thing happens if they try to go direct to the beta page and click 'sign in'.

**Comment by alexkyllo** [comment]
Not a bug, this is just how the invite system works. The code that creates Users checks that the e-mail address the invite was sent to matches the e-mail address on the g+/gmail account they authenticated with. This is the only way it can tell whether a user was invited or not, until we implement a unique invite token system.

**Comment by alexkyllo** [comment]
Not a bug, this is just how the invite system works. The code that creates Users checks that the e-mail address the invite was sent to matches the e-mail address on the g+/gmail account they authenticated with. This is the only way it can tell whether a user was invited or not, until we implement a unique invite token system.
