### ISSUE TITLE
Cannot modify effect size for studies in newly created articles

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#151]
Steps:
1. Create an article and add a study
2. Input an effect size (e.g., d = .2; it doesn't matter which effect size is inputted)
3. Save study, go back to home page and return to article
4. Attempt to modify effect size

Notice nothing happens when you click on the effect size value, and hence effect size cannot be modified.

Notes: 
<li>After inputting an effect size and saving the study, I can actually modify it if I don't leave the page. However, if I leave the page and come back to it, I can no longer modify the effect size.</li>
<li>Modifying all other fields in this way works as expected.</li>
<li>This seems to *only* be happening for newly created articles. If I go to an article I created a long time ago (e.g., https://www.curatescience.org/beta/#/articles/59309), I actually *can* modify effect sizes.</li>

**Comment by manzhikov** [comment]
https://github.com/ScienceCommons/www/pull/13
