### ISSUE TITLE
Cannot save manually added article ("article not found")

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#162]
Steps: 
1.  On Add article page, enter a title, a year, and one author
2. Click Save
Notice error: "Article not found"

Note: one *can* edit and successfully save an existing article (e.g., https://www.curatescience.org/beta/#/articles/335170)

Also of note: this issue also occurs on the staging website, however, one *can* successfully save a newly added article if the article metadata is retrieved via "Retrieve article metadata" button (https://curatescience-staging.herokuapp.com/beta/#/articles/new). This is kind of strange; if one just enters the same valid DOI (without hitting ENTER; e.g., 10.1111/1475-6811.00023), then manually enters an author, a year, and a title, then hit save, it doesn't work and yields the same error ("Article not found"). 

Finally, for staging website, one *cannot* edit and save an existing article (though one *can* do this on the production website, see above), which yields a different error (i.e., "unknown error").

**Comment by alexkyllo** [comment]
Save function in BaseData.js was directing save actions to the wrong URL. This commit fixes the issue. I successfully added https://www.curatescience.org/beta#/articles/335181 manually after making this change.

**Comment by alexkyllo** [comment]
I think the staging site is still erroring on article save because it's trying to update the ElasticSearch index and failing. I still have some work to do on staging to get ES working correctly.
