### ISSUE TITLE
Improve login page to clarify workflow for non-invited users

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#186]
Now that we have the beta site working for unauthenticated users, I just noticed that if a non-invited user clicks on "log in to edit/add..." on an article page, they're brought to the login page, but it's completely unclear that they actually *cannot* login if they haven't been invited. Hence, login page needs to be improved as follows:
![login-page-issue](https://cloud.githubusercontent.com/assets/4512335/8551979/09fc300c-24a8-11e5-8bc0-8e0843fc6755.png)

The following change also needs to be implemented:
In the event a non-invited user nonetheless tries to login on this page, they should get a message popup that states: <i>"You are attempting to log in using an email address that has not been invited into the system. Please use the email address with which you were invited into the system or register to be notified when our public Beta will be ready."</i>, and remain on the login page. Currently non-invited users trying to login end up on the Sign up section of the landing page (https://www.curatescience.org/#section-6)

Steps to reproduce this last issue:
1. Go to login page, https://www.curatescience.org/beta#/login
2. Attempt to sign in using a gmail address that has *not* been invited into the system (i.e., *not* on the whitelist)

RESULT: After giving Curate Science permission to access Google+ account info, notice that you end up on the Sign up section of the landing page (https://www.curatescience.org/#section-6)

EXPECTED: User should get a message along the lines of: <i>"You are attempting to log in using an email address that has not been invited into the system. Please use the email address with which you were invited into the system or register to be notified when our public Beta will be ready."</i> and remain on the login page.

This link might provide a clue to how to fix the problem:
https://www.curatescience.org/auth/failure?message=csrf_detected&strategy=google_oauth2

**Comment by alexkyllo** [comment]
Deployed to staging and PRs opened.

**Comment by eplebel** [comment]
Just tested this, and it appears that non-invited users still end up on the signup section of the landing page (https://www.curatescience.org/#section-6), instead of receiving the pop-up flash message and staying on the login page.

**Comment by alexkyllo** [comment]
Are you sure you tested it on staging and not production? 
https://curatescience-staging.herokuapp.com/beta/#/login

I can't reproduce your issue on staging--I just tested it on staging and it worked as expected:
![image](https://cloud.githubusercontent.com/assets/2609312/8656576/3ca51308-294d-11e5-997a-f4102181b8b8.png)

**Comment by eplebel** [comment]
Oops, because of the potential issue with our automatic deployment process (see my email) -- whereby changes were already showing up in production -- I only tested in production assuming staging and production were the same. However, I just tested this in staging and can see that it's working, sorry about that!

So that's even potentially weirder that only some of the changes were automatically deployed to production??

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
July 13, 2015 1:56PM email to @alexkyllo :

it seems (though i'm not 100% sure on this) that when you (or anyone else probably) push changes to staging and then open a pull request into master (not sure if this part is critical), the changes are automatically being deployed into production. i've suspected this before, but for the latest changes, i'm pretty sure this is happening because your changes to the improved login page (https://github.com/ScienceCommons/www/commit/1cf57843225b20eee7027ffce8b8e498900411f6) are already showing up in production (https://www.curatescience.org/beta/#/login) even though i haven't merged the changes into the master branch. 

this is particularly weird, because when i go to Travis-CI dashboard (https://travis-ci.org/ScienceCommons/www/builds), it's clear that the changes have *NOT* been deployed to the master branch..... WEIRD!!

**Comment by eplebel** [comment]
Minor point regarding the flash message: 
The message stays at the top of the screen even once you browse away from the login page. The only way to get rid of the message appears to be by reloading the page (e.g., go to home page, and once on home page, click refresh (F5); though I just realized simply reloading the login page also dismissed the message). 

Could this be changed so that the flash message gets dismissed once the user browses away from the page?

**Comment by alexkyllo** [comment]
This will be a little tricky because it's a single page app, so the server
doesn't know when the user navigates to a different "page"--the page
transitions are all just client-side javascript. And the flash message must
be rendered server-side.

An easier way might be to use some JavaScript to make the flash message
dismissable (with an 'X' button) or have it automatically disappear after a
few seconds, or both. What do you think?

**Comment by eplebel** [comment]
>>>>An easier way might be to use some JavaScript to make the flash message
dismissable (with an 'X' button) or have it automatically disappear after a
few seconds, or both. What do you think?

That would be awesome! 
I'd say have an 'X' button that users can click to dismiss the message *and* also automatically dismiss it after 5 seconds.

**Comment by alexkyllo** [comment]
https://github.com/ScienceCommons/api/pull/217
