### ISSUE TITLE
navbar collapse problem on landing page

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#187]
when the navbar collapses for screens smaller than 980px (wide) , the menu burger icon doesn't reveal the navbar links (i.e., About, Articles, Features, etc.)

**Comment by alexkyllo** [comment]
Hi, I just fixed this in a commit to staging: https://github.com/ScienceCommons/api/commit/246e4be7710d3a05a28b3afddb666ebe9a6905da

Speaking of which, do you want me to merge staging into master to deploy the latest round of changes to production, or is there a reason to wait?

**Comment by eplebel** [comment]
Great and and sure go ahead and merge!!

**Comment by alexkyllo** [comment]
https://github.com/ScienceCommons/api/commit/c29230820c1ff8f288c4e981c169c02cfba77c1c
