### ISSUE TITLE
Give unauthenticated users read-only access to entire beta app

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#188]
As per email correspondence with @alexkyllo :

The API side will need to be changed to give unauthenticated users access to certain API endpoints like /articles, /authors, /studies, but not others like /bookmarks. They will be able to do GET requests on those resources only. Redirect logic will need changes so that anonymous users do not always get redirected to the login page, but are able to access it from the menu, and authenticated users cannot access it at all (they are already logged in). There will be several nuances to this, and many tests to execute everything is working as intended.

The client side will also need to be changed to make all the "edit", "save","delete" etc. buttons disappear for anonymous unauthenticated users. Otherwise they would think they are editing until they hit save and their request fails with 401 Unauthorized (great point!).

**Comment by alexkyllo** [comment]
@eplebel what should happen when an unauthenticated user clicks on a cell in the StudyTable and that cell has no content? 

Correct me if I'm wrong, but I'm assuming that unauthenticated users should not be able to edit study data nor add comments. (If you do allow these things you will get bots entering spam).

As you can see from this screenshot, I've disabled the edit button and comment box for unauthenticated users, but as a result the modal is basically blank. Do you want some placeholder text? A link to the login page saying something like "Please log in to edit or comment"? Do you want the modal to not pop up at all for unauthenticated users? Let me know, thanks!

![screenshot from 2015-06-29 06 56 26](https://cloud.githubusercontent.com/assets/2609312/8409356/32a81cbe-1e2c-11e5-8476-817d75bfbd7c.png)

**Comment by eplebel** [comment]
Do you want some placeholder text? A link to the login page saying something like "Please log in to edit or comment"?

Yes, that sounds perfect (i.e., add "Please log in to edit or comment" with "log in" hyperlinked to the login page). Please make sure to also do this for the study components window(s), where the "Add a link" button will be missing for unauthenticated users.

**Comment by alexkyllo** [comment]
Ok, this portion of the issue is done, now I am working on the backend (securing the API endpoints and writing/fixing tests).
