### ISSUE TITLE
cannot delete one's own comments 

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#200]
leave a comment on study components or study info (or general comment); notice how you cannot delete your comment. 

this used to actually work, though i don't remember how long ago. i could delete comments directly from the article page (e.g., https://www.curatescience.org/beta/#/articles/107910) and could also delete comments from my profile page (https://www.curatescience.org/beta/#/profile)

**Comment by eplebel** [comment]
this seems to be working again (on both staging and production), though i have no idea why!

**Comment by alexkyllo** [comment]
Cool. My guess is that my fix for issue #212 fixed this as a side effect.
