### ISSUE TITLE
replace CS logo on beta website with CS Beta logo

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#203]
Replace CS logo on beta website with CS Beta logo, as was recently done on landing page (https://curatescience.org/). 

This needs to be done for the large billboard logo on the main beta page (https://www.curatescience.org/beta/#/) and also for the smaller logo on the top left part of the navbar , displayed for the remaining pages (search results, article page, profile page, etc.)

**Comment by alexkyllo** [comment]
So, I can replace the current logo with the Beta logo that Lee sent, but the fonts look different. What do you want to do?

![screenshot from 2015-07-15 22 28 53](https://cloud.githubusercontent.com/assets/2609312/8716103/22f7f0b0-2b41-11e5-80a8-fb11fda737a6.png)


![screenshot from 2015-07-15 22 28 39](https://cloud.githubusercontent.com/assets/2609312/8716097/0a072954-2b41-11e5-950d-68b30c1d004e.png)

**Comment by eplebel** [comment]
ya i really don't understand .svg files apparently (it also looked different when i opened them with Chrome)... @smack416 any ideas what's going on here?

**Comment by alexkyllo** [comment]
added beta logo in staging and opened PR, check it out on staging site and merge if it looks good to you (make sure to disable cache so your browser downloads the updated logo):
https://github.com/ScienceCommons/www/pull/43
https://curatescience-staging.herokuapp.com/beta

**Comment by smack416** [comment]
Excellent! Glad this worked out.
