### ISSUE TITLE
article page with anonymous comment doesn't load for unauthenticated users

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#212]
it says: TypeError: ctrl.listController.user is undefined and Uncaught TypeError: Cannot read property 'get' of undefined (main.js:7011:35)

example article with an anonymous comment: https://curatescience-staging.herokuapp.com/beta/#/articles/335236

**Comment by alexkyllo** [comment]
https://github.com/ScienceCommons/www/pull/38
