### ISSUE TITLE
Articles section text of profile page needs to be revised

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#214]
It currently says:

"You have no articles. You can link articles by searching for them and then requesting to be linked."

This is not accurate and current functionality not yet implemented.

Hence, this needs to be changed to:

"Articles you have authored and linked to your user account will soon appear here."

**Comment by eplebel** [comment]
I updated the text directly in the app/assets/javascripts/beta/main.js file (https://github.com/ScienceCommons/api/commit/cfe905aaac73e72062ed925a9deff187950cfcd4) and then remembered that this is *not* how the app works, and hency why my changes didn't work (rather main.js is automatically compiled).

I couldn't figure out what source files to change so that the text is updated via this automatically generated main.js

**Comment by alexkyllo** [comment]
Fixed https://github.com/ScienceCommons/www/commit/33462861b5e42a21ac9c641940f61f1a4fe32dde
