### ISSUE TITLE
when replication study added, all replication studies (including pre-existing ones) are incorrectly hidden

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#216]
replication studies now expand by default upon page load, but @manzhikov 's changes (https://github.com/manzhikov/www/commit/fd4062635ed1fffb103f3cfe9462f1f6fcfaec94) has now caused a bug whereby when a replication study is added, all replication studies (including pre-existing ones) are incorrectly hidden.

Steps:
1. On an article page with at least one original and replication study (e.g., https://curatescience-staging.herokuapp.com/beta/#/articles/335246), click the add replication icon to add a replication study
2. On the add replication window, search "Pashler" and for the first article ((2011) LeBel & Pashler - jpsp), add  LeBel & Pashler (2011) as a replication study

Notice that the replication study is added, however, all replication studies are now hidden in the replication table. Note that if you close the add replication window and click the expand replications icon, the replication studies *are* revealed.

**Comment by alexkyllo** [comment]
I think I've fixed this issue with this change, just pushed to staging so you can test it out there. 
https://github.com/ScienceCommons/www/commit/f2909a48c43db35e69cb09a6347a6b1257adb57b 

PR opened: https://github.com/ScienceCommons/www/pull/45

**Comment by eplebel** [comment]
The problem *does* seem to have been fixed, however, after adding/linking a replication study, the "Add replication" window unexpectedly disappears (the logic of keeping it open is that a user will often be adding/linking more than one replication study to an original study).

**Comment by alexkyllo** [comment]
Oh, ok. I wasn't sure what behavior you wanted there. That's what line 214 that was commented out does, it closes the modal when you link a replication. I had uncommented it, but I just went in and deleted it. Travis will deploy that to staging in a minute or two.

**Comment by eplebel** [comment]
Great, thanks for the quick fix!!
