### ISSUE TITLE
Activate blue version of study component icons for articles on homepage

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#222]
Activate the blue version of the study component icons if a recently added/updated article contains a study that has ANY of those components (except for disclosure icon, given that one hasn't yet been implemented anywhere on the site). 

For instance, if a study has at least 1 study with available data/syntax, then the data/syntax icon would be blue on the homepage. For example, the Donnellan et al. (2015 , https://www.curatescience.org/beta/#/articles/60045) would have the first two icons activated in blue because it has at least one study with availabel data/syntax *and* materials.

Mockup:
![basic-homepage-enhancements](https://cloud.githubusercontent.com/assets/4512335/8761657/496c6448-2d2a-11e5-807a-784ae8754ff5.jpg)

**Comment by alexkyllo** [comment]
Done, deployed to staging and pull requests opened:
https://github.com/ScienceCommons/www/pull/46
https://github.com/ScienceCommons/api/pull/228

**Comment by eplebel** [comment]
Sweet, that's so awesome!!
