### ISSUE TITLE
allow anyone to login with gmail address -- i.e., no more whitelist

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#231]
at this point i think we can just let anyone log in with a valid gmail address (while i'm giving talks, i don't want to have to individually invite each person that wants to log into the system). actually, i'm unclear why we even implemented this type of invite system to begin with (other than something about gradual server load increases in cases of rapid user growth).

and then we could send them a welcome email with some brief info on how they contribute / engage with the site (instead of the invite email)?

**Comment by alexkyllo** [comment]
@eplebel Ok, I can turn the invite checking off by deleting like one line of code. What do you want the login page https://www.curatescience.org/beta/#/login to say, though?

And do you also want me to work on adding a new feature to send a welcome e-mail upon first login? If so, can you send me the text you'd like that e-mail to contain?

**Comment by eplebel** [comment]
I guess , just delete the first two lines (i.e., "Our Beta is currently by invitation only." and "If you have been invited:" 

Also, delete the "Otherwise:" and changed the next line to: "For news and updates about Curate Science, please sign up to our email newsletter below:"

I'm still working on the welcome email, so for now let's just not have a welcome email, thanks!!

**Comment by eplebel** [comment]
great, thanks for the quick turn around on this!!
i guess now we're unofficially in "public beta" mode given anyone with a valid gmail address can log in! (i may make an official announcement on our twitter feed in the next couple of days....)
