### ISSUE TITLE
send welcome email to user upon first login

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#239]
email text is below. also, as is standard with Mailchimp newsletter emails, we should make sure to have the "unsubscribe from this list" and "update subscription preferences"  links at the bottom of the email, so that users can unsuscribe and/or modify their email notification preferences.

**************************************************
Welcome to Curate Science!

We’re very glad you’ve decided to join the Curate Science community. Curate Science is a web application that facilitates the independent verification of published findings, as to accelerate the rate of cumulative knowledge and innovation.

To get started, here are some example things you can do on Curate Science: 
•	Link replications to original studies
•	Add links to open data/materials (i.e., publicly available files) to original or replication studies
•	Curate study information for seminal articles in your own research area
•	Endorse the analytic reproducibility of results for studies with open data ([example](https://www.curatescience.org/beta/#/articles/49900), see Donnellan et al., 2015, Study 1 under Data/Syntax)
•	Add comments involving nuanced interpretations of replication results and/or add links to external commentary ([example #1](https://www.curatescience.org/beta/#/articles/335270), [example #2](https://www.curatescience.org/beta/#/articles/335238))
•	Add/update “community abstract” that updates interpretation of findings in light of follow-up (replication) research ([example](https://www.curatescience.org/beta/#/articles/335238))

For help in doing any of these things, please refer to the “How-To” and “FAQ”. If you still need help, please don’t hesitate to contact us at [support@curatescience.org](mailto:support@curatescience.org).

Only have a bit of time to contribute? That’s OK! The spirit of Curate Science involves an incremental piecemeal approach to curation and verification. Any small contribution helps! Other users will follow up where you left off!

We really need your feedback about ways to improve Curate Science to make it easier for you to use, whether it’s improving an existing feature or implementing a brand new feature. We’d also appreciate feedback about how to improve Curate Science so that you’re more motivated to engage with the website and contribute content. To provide feedback -- no matter how brief or negative – please click on the Feedback tab located at the bottom-right of any page.

If you share our vision, please spread the word about Curate Science, thanks!

Sincerely,
Curate Science Team

**Comment by alexkyllo** [comment]
Added the welcome email to the mailchimp list.

**Comment by eplebel** [comment]
So users will receive a welcome email upon first log in right? (Cant test
this right now)

**Comment by alexkyllo** [comment]
Yep, I just tested it.

**Comment by eplebel** [comment]
Nice, thanks so much!!!

**Comment by eplebel** [comment]
this doesn't seem to work, just tested it by logging in for the first time with "cs@curatescience.org" and i did *not* receive the welcome email (waited 5 minutes , and even checked spam folder).

this needs to work for any user, not just users on the mailchimp list

**Comment by alexkyllo** [comment]
Mailchimp can't do that, it can only send email to people on a mailing list. It will send the welcome email when they sign up for the list. You can't subscribe someone to a Mailchimp list, they have to voluntarily subscribe. 

We may be able to send a welcome email from the rails app upon first login using Mandrill though, do you have a Mandrill account?

**Comment by eplebel** [comment]
OK i've just created a Mandrill account for us and have sent you the login info via email. 

For now, I guess I can just manually email a slightly modified version of the welcome email to our newsletter subscribers to invite them to log into the system and start poking around / contributing. (slightly modified meaning it needs to include a link to login)

**Comment by alexkyllo** [comment]
Just sent you a sample of the welcome e-mail from Mandrill.
