### ISSUE TITLE
hyperlink linked study components

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#248]
hyperlink linked study components , that is, hyperlink the data/syntax files, materials files, and pre-registration files to their respective URLs

e.g.
the linked file "ML3AllSitesandmTurk.csv" for [R. Ebersole et al. (2015) Study 1](https://www.curatescience.org/beta#/articles/335254), should be hyperlinked to this [URL] (https://osf.io/pftdg/?action=download&version=1) so that users can download it directly (as they're most familiar with) instead of having to click on our weird download icon (which eventually will likely be removed)

**Comment by alexkyllo** [comment]
https://github.com/ScienceCommons/www/pull/55

**Comment by eplebel** [comment]
Great, thanks for the quick turnaround on this! It's working, but just noticed that clicking on links doesn't open in a new window as the "download button" is currently working.

e.g. for this [article] (https://curatescience-staging.herokuapp.com/beta#/articles/335261), clicking on [SurveyMonkeyLink] (https://www.surveymonkey.com/r/?sm=v4QmCWVIZNBzSqDasBAwDdHIPS8PEDAuAkckT5cIA%2bKgXfX%2f7QuLL%2fLHg7DjZIHY7UbJCgOX1KNlWaz5tERqk9OXHOEwplZSzSncMOhgIQk%3d) should open the link in a new window/tab instead of in the current window

**Comment by alexkyllo** [comment]
OK, links should open in new tab or window (depending on your browser settings) now.

**Comment by eplebel** [comment]
great!
