### ISSUE TITLE
hyperlink DOI text strings to their respective DOI resolver URL

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#251]
e.g.
on article page https://www.curatescience.org/beta/#/articles/335301,

the DOI 10.1111/j.1467-9280.2007.01983.x should be hyperlinked to "https://dx.doi.org/10.1111/j.1467-9280.2007.01983.x", which automatically redirects user to journal article page , in our e.g., http://pss.sagepub.com/content/18/9/803

**Comment by alexkyllo** [comment]
Pushed to staging and https://github.com/ScienceCommons/www/pull/57 opened.
