### ISSUE TITLE
Improve labeling within the Add replication window

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#83]
Currently, it's unclear how to add a replication study within the "Add a replication" window.

I think at the very least we should display the study number and make it *and* the replication icon selectable.  Perhaps something along the lines of:
![add-a-replication-window2](https://cloud.githubusercontent.com/assets/4512335/4928922/b7dc84ec-654a-11e4-828f-e23e4a576707.png)

We should also remove the IVs vs DVs at this point because these will likely be empty and it just looks weird and confusing (perhaps we could consider re-adding some form of this down the road).

Also, for articles without studies, we should add a link that users can click on that brings them directly that article so they can add a study/studies.

**Comment by alexkyllo** [comment]
Closed with pull request https://github.com/ScienceCommons/www/pull/4
